name: go
on: [push, pull_request]
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: '1.14'
    - run: go build ./...
    - run: go test ./...
    - run: docker-compose up -d
    - run: go test --tags=examples ./...

