name: docs
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2.3.5
     - run: sudo apt-get install python3-sphinx
     - run: make html
       working-directory: docs
